config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :exponats
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/exponat.rb
require 'uri'
class Exponat < ActiveRecord::Base
  belongs_to :user
  validates :link, presence: true
  validate :is_link_a_url?

  def is_link_a_url?
    uri = URI.parse(link)
    if (uri.kind_of?(URI::HTTP))
      return true
    else      
      errors.add(:link, "should be URL")
      return false
    end
    rescue URI::InvalidURIError
      false
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
   has_attached_file :item,
                    :storage => :s3,
                    # :s3_credentials => Proc.new{|a| a.instance.s3_credentials }, 
                    styles: { medium: "800x800>", thumb: "300x300>" }, 
                    default_url: ":styles/get_tradie.png"
  validates_attachment_content_type :item, content_type: /\Aimage\/.*\Z/
  validates_attachment_size :item, less_than: 2.megabytes

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :exponats
  has_many :images
  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exponats_controller.rb
class ExponatsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create,:edit, :update, :destroy]
  before_action :set_exponat, only: [:show, :edit, :update, :destroy]
  before_action :check_rights, only: [:edit, :update, :destroy]


  # GET /exponats
  # GET /exponats.json
  def index
    @exponats = Exponat.all
  end

  # GET /exponats/1
  # GET /exponats/1.json
  def show
  end

  # GET /exponats/new
  def new
    @exponat = Exponat.new
  end

  # GET /exponats/1/edit
  def edit
  end

  # POST /exponats
  # POST /exponats.json
  def create
    @exponat = current_user.exponats.new(exponat_params)
    # Exponat.new(exponat_params)

    respond_to do |format|
      if @exponat.save
        format.html { redirect_to @exponat, notice: 'Exponat was successfully created.' }
        format.json { render :show, status: :created, location: @exponat }
      else
        format.html { render :new }
        format.json { render json: @exponat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exponats/1
  # PATCH/PUT /exponats/1.json
  def update
    respond_to do |format|
      if @exponat.update(exponat_params)
        format.html { redirect_to @exponat, notice: 'Exponat was successfully updated.' }
        format.json { render :show, status: :ok, location: @exponat }
      else
        format.html { render :edit }
        format.json { render json: @exponat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exponats/1
  # DELETE /exponats/1.json
  def destroy
    @exponat.destroy
    respond_to do |format|
      format.html { redirect_to exponats_url, notice: 'Вы удалили элемент из медиа-коллекции' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exponat
      @exponat = Exponat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exponat_params
      params.require(:exponat).permit(:link, :item_type)
    end

    def check_rights
      if @exponat.user != current_user  
        respond_to do |format|
          format.html { redirect_to root_url, alert: 'Вы пытаетесь совершить деструктивные действия с чужим контентом' }
          format.json { head :no_content }
        end
      end    
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create,:edit, :update, :destroy]
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :check_rights, only: [:edit, :update, :destroy]

  

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id,:item)
    end

    def check_rights
      if @image.user != current_user  
        respond_to do |format|
          format.html { redirect_to root_url, alert: 'Вы пытаетесь совершить деструктивные действия с чужим контентом' }
          format.json { head :no_content }
        end
      end    
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exponats_helper.rb
module ExponatsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/exponats/_form.html.erb
<%= simple_form_for(@exponat, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :link %>
    <%= f.input :item_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/exponats/edit.html.erb
<h1>Editing Exponat</h1>

<%= render 'form' %>

<%= link_to 'Show', @exponat %> |
<%= link_to 'Back', exponats_path %>

app/views/exponats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exponats</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Item type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exponats.each do |exponat| %>
      <tr>
        <td><%= image_tag exponat.link, class: "thumbnail" %></td>
        <td><%= exponat.item_type %></td>
        <td><%= link_to 'Show', exponat %></td>
        <td><%= link_to 'Edit', edit_exponat_path(exponat) %></td>
        <td><%= link_to 'Destroy', exponat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exponat', new_exponat_path %>

app/views/exponats/new.html.erb
<h1>New Exponat</h1>

<%= render 'form' %>

<%= link_to 'Back', exponats_path %>

app/views/exponats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @exponat.link %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @exponat.item_type %>
</p>

<%= link_to 'Edit', edit_exponat_path(@exponat) %> |
<%= link_to 'Back', exponats_path %>

app/views/images/_form.html.erb
<%= simple_form_for(@image) do |f| %>
  <%= f.error_notification %>

  <div class="form-group input-group">
    <%= f.label :item, class: "control-label input-group-addon" %>
    <%= f.file_field :item, class: "form-control" %>
    <p class="input-group-addon extra">Maximum file size: 2MB.</p>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user %></td>
        <td><%= image_tag image.item.url(:thumb), class: "thumbnail" %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @image.user %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Редактировать аккаунт', edit_user_registration_path %></li>
  <li><%= link_to 'Выход', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Вход', new_user_session_path %></li>
  <li><%= link_to 'Регистрация', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Галерея', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'О проекте', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Eduson Test" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Eduson Test" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
  <div class="container">
   <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Тестовый проект 2016</p>
            </div>
        </div>
    </footer>
  </div>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>О сайте<% end %>
<h3>О сайте</h3>
<p>Это тестовый проект, реализующий медиа-галерею с сылками и изображениями.
</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Пользователи</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Пользователь</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-12">
            <h1 class="page-header">Thumbnail Gallery</h1>
        </div>

        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="http://placehold.it/400x300" alt="">
            </a>
        </div>
    </div>

    <hr>

   
</div>
<!-- /.container -->